# Generated by Django 5.0.6 on 2025-02-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'STUDENT'), ('teacher', 'TEACHER'), ('school_admin', 'SCHOOL_ADMIN'), ('school_head', 'SCHOOL_HEAD'), ('district_admin', 'DISTRICT_ADMIN')], max_length=30),
        ),
    ]
