# Generated by Django 5.0.6 on 2025-01-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customadmin', '0002_remove_customuser_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
    ]
