# Generated by Django 5.0.6 on 2025-02-28 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('district', '0001_initial'),
        ('schoolconfig', '0001_initial'),
        ('student', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('on_medical_leave', models.BooleanField(blank=True, default=False, null=True)),
                ('on_vocational_leave', models.BooleanField(blank=True, default=False, null=True)),
                ('position', models.CharField(blank=True, choices=[('Permanent', 'Permanent'), ('Substitute', 'Substitute')], max_length=10, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.academiccalendar')),
                ('assigned_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_class', to='student.classroom')),
                ('base_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='base_subject_teacher_profiles', to='schoolconfig.schoolsubject')),
                ('classes_taught', models.ManyToManyField(related_name='teacher', to='student.classroom')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='schoolconfig.schoolprofile')),
                ('subjects_taught', models.ManyToManyField(related_name='teacher_subjects', to='schoolconfig.schoolsubject')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
