# Generated by Django 5.0.6 on 2025-02-15 09:50

import django.db.models.deletion
import teacher.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
        ('schoolconfig', '0001_initial'),
        ('teacher', '0002_assignment_assignmentsubmission_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='academic_year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.academiccalendar'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolconfig.schoolsubject'),
        ),
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to=teacher.models.dynamic_upload_path),
        ),
    ]
