# Generated by Django 5.0.6 on 2025-01-20 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0008_schooladminprofile_alter_schoolprofile_school_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladminprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customsettings.schoolprofile'),
        ),
    ]
