# Generated by Django 5.0.6 on 2025-01-21 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0009_alter_schooladminprofile_school'),
        ('district', '0008_alter_academiccalendar_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladminprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district_school_registration'),
        ),
    ]
