# Generated by Django 5.0.6 on 2025-01-22 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0010_alter_schooladminprofile_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladminprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
