# Generated by Django 5.0.6 on 2025-01-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0012_schooladminprofile_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schooladminprofile',
            old_name='date_joined',
            new_name='date_created',
        ),
    ]
