# Generated by Django 5.0.6 on 2025-01-28 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customsettings', '0013_rename_date_joined_schooladminprofile_date_created'),
        ('district', '0010_schoolheadprofile_head'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school_admin',
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='school',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='district.district_school_registration'),
        ),
    ]
