# Generated by Django 5.0.6 on 2025-02-08 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grading', '0001_initial'),
        ('schoolconfig', '__first__'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='select_classes',
            field=models.ManyToManyField(to='student.classroom'),
        ),
        migrations.AddField(
            model_name='capture',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolconfig.schoolsubject'),
        ),
        migrations.AddField(
            model_name='capturedclassroom',
            name='capture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grading.capture'),
        ),
        migrations.AddField(
            model_name='capturedclassroom',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.classroom'),
        ),
        migrations.AddField(
            model_name='getmark',
            name='captured_classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grading.capturedclassroom'),
        ),
        migrations.AddField(
            model_name='getmark',
            name='student',
            field=models.ManyToManyField(related_name='marks', to='student.studentprofile'),
        ),
    ]
