# Generated by Django 5.0.6 on 2025-02-19 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladminprofile',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolconfig.schoolprofile'),
        ),
    ]
