# Generated by Django 5.0.6 on 2025-02-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classname',
            name='classname',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J')], max_length=1),
        ),
    ]
