# Generated by Django 5.0.6 on 2025-03-12 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolconfig', '0002_alter_classname_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolprofile',
            name='school_subjects',
        ),
    ]
