# Generated by Django 5.0.6 on 2025-02-24 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='subjects',
        ),
    ]
