# Generated by Django 5.0.6 on 2025-03-13 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectsmanager',
            old_name='id',
            new_name='cid',
        ),
    ]
