# Generated by Django 5.0.6 on 2025-03-14 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_rename_id_subjectsmanager_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectsmanager',
            name='subject_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
