# Generated by Django 5.0.6 on 2025-02-25 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0002_remove_schoolheadprofile_head_district_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='district_school_registration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='district_school_registration',
            name='updated_at',
        ),
    ]
