# Generated by Django 5.0.6 on 2025-03-12 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0003_remove_district_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
