# Generated by Django 5.0.6 on 2025-03-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0004_subjects_color_alter_subjects_id'),
        ('schoolconfig', '0002_alter_classname_classname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subjects',
            new_name='SubjectsManager',
        ),
    ]
