# Generated by Django 5.0.6 on 2025-03-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0005_rename_subjects_subjectsmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectsmanager',
            name='subjects',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
