# Generated by Django 5.0.6 on 2025-01-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0007_alter_district_school_registration_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='academic_year',
            field=models.PositiveIntegerField(blank=True, default=2025, null=True),
        ),
        migrations.DeleteModel(
            name='SchoolAdminProfile',
        ),
    ]
