# Generated by Django 5.0.6 on 2025-01-23 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0008_alter_academiccalendar_academic_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolheadprofile',
            old_name='phone_number',
            new_name='address',
        ),
        migrations.AddField(
            model_name='schoolheadprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoolheadprofile',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schoolheadprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolheadprofile',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolheadprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schoolheadprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='school_head_profiles/'),
        ),
    ]
