# Generated by Django 5.0.6 on 2025-01-24 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('district', '0009_rename_phone_number_schoolheadprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolheadprofile',
            name='head',
            field=models.CharField(blank=True, choices=[('head1', 'head1'), ('head2', 'head2')], max_length=10, null=True),
        ),
    ]
