# Generated by Django 5.0.6 on 2025-03-14 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_initial'),
        ('schoolconfig', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='academic_year',
        ),
        migrations.AddField(
            model_name='assignment',
            name='classrooms',
            field=models.ManyToManyField(to='student.classroom'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolconfig.schoolprofile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schoolconfig.schoolsubject'),
        ),
    ]
